version: '3.7'
services:
  nginx:
    container_name: core_web
    restart: on-failure
    image: nginx:stable
    volumes:
      - ~/nginx/nginx.dev.conf:/etc/nginx/conf.d
      - static_volume:/app/static
    command: sh -c "mkdir -p /etc/nginx/conf.d/ && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    container_name: core_app
    build: .
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    command: >
      sh -c " python manage.py migrate &&
                gunicorn testapp.wsgi:application --bind 0.0.0.0:5000"
    links:
      - db
    volumes:
      - .:/app
      - static_volume:/app/static
    depends_on:
     - db
     
  db:
    container_name: core_db
    image: postgres:14.1-alpine
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    driver: local
  static_volume:
    driver: local