version: '3.7'
services:
  nginx:
    container_name: core_web
    restart: on-failure
    image: nginx:stable
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    container_name: core_app
    build: .
    restart: always
    env_file: .env
    expose:
      - "8000"
    command: gunicorn --bind 0.0.0.0:8000 testapp.wsgi --workers=4
    volumes:
      - .:/app
      - static_volume:/app/static
    depends_on:
     - db
     
  db:
      container_name: core_db
      image: postgres:12.0-alpine
      env_file: .env
      volumes:
        - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    driver: local
  static_volume:
    driver: local